---
- name: Create VM from Template
  vmware_guest:
    validate_certs: False
    hostname: "{{ vmware_host }}"
    username: "{{ vmware_user }}"
    password: "{{ vmware_password }}"
    datacenter: "{{ vmware_datacenter }}"
    name: "{{ vm_name}}"
    template: "{{ vm_template }}"
    folder: "{{ vm_folder  }}"
    disk:
      - size_gb: "{{ vm_disk_size  }}"
        type: thin
        datastore: "{{ vm_datastore }}"
    networks:
      - name: "{{ vm_network }}"
        device_type: "vmxnet3" 
    hardware:
      memory_mb: "{{ vm_memory | default(4096) }}"
    wait_for_ip_address: True
    state: poweredon
  register: newvm
    
- name: Register newvm as a dummy host
  add_host:
    name: "NEW_VM_HOLDER"
    ansible_host: "{{ newvm.instance.ipv4  }}"
    newvm: "{{ newvm  }}"

- name: debug1
  debug:
    msg: "{{ hostvars['NEW_VM_HOLDER'].newvm.instance.ipv4  }}"
