---
- hosts: webserver, database-server
  name: Gather facts
  tasks: [ ]

- name: Install Webserver, Wordpress, and PHP
  hosts: webserver
  remote_user: root

  roles:
    - common
    - php
    - wordpress
    - httpd

- name: Install Database Server
  hosts: database-server
  remote_user: root

  roles:
    - common
    - mariadb
