---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: wordpress
  remote_user: root
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - mariadb
    - php
    - wordpress
    - httpd
