---
- name: Install php deps
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-enchant
    - php-IDNA_Convert
    - php-mbstring
    - php-mysql
    - php-PHPMailer
    - php-process
    - php-simplepie
    - php-xml

